version: '3.8'

services:
  star_wars_wiki:
    build:
      context: .
      dockerfile: Dockerfile
    image: star_wars_wiki
    container_name: star_wars_wiki
    restart: unless-stopped
    ports:
      - '8000:8000'
